## Customer Segmentation 

### Importing the libraries

In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler

### Importing the dataset

In [28]:
dataset = pd.read_csv('Customer Analysis.csv')

In [29]:
dataset.head()

Cust Id  RFM  Recency  Frequency   Monetory Value 
0    85775  444      117        131           9431.53
1    85775  444      159        127         221208.19
2    85775  444      264        102           9874.84
3    85775  444      136         93           3909.32
4    85775  444      136         85         124324.13

In [30]:
X = dataset.iloc[:, 2:5].values

In [31]:
X

array([[1.1700000e+02, 1.3100000e+02, 9.4315300e+03],
       [1.5900000e+02, 1.2700000e+02, 2.2120819e+05],
       [2.6400000e+02, 1.0200000e+02, 9.8748400e+03],
       ...,
       [3.5000000e+02, 1.0000000e+00, 1.6000000e+02],
       [3.4900000e+02, 1.0000000e+00, 7.0000000e+01],
       [2.4000000e+02, 1.0000000e+00, 1.0500000e+02]])

In [34]:
sc_X = StandardScaler()

In [35]:
X = sc_X.fit_transform(X)

In [36]:
X

array([[-1.77458561, 31.30929355,  1.13516494],
       [-1.05022369, 30.33278591, 36.6765897 ],
       [ 0.76068112, 24.2296132 ,  1.20956346],
       ...,
       [ 2.24389839, -0.42720458, -0.42082988],
       [ 2.22665168, -0.42720458, -0.43593413],
       [ 0.34676002, -0.42720458, -0.43006026]])

### Using elbow method to find the optimal number of clusters

In [ ]:
from sklearn.cluster import KMeans
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

### Training the K-Means model on the dataset

In [23]:
kmeans = KMeans(n_clusters = 4, init = 'k-means++', random_state = 42)
y_kmeans = kmeans.fit_predict(X)

In [24]:
y_kmeans

array([2, 2, 2, ..., 1, 1, 1])

In [25]:
dataset['Predicted class'] = y_kmeans

In [26]:
dataset.to_csv('Customer RFM Segment.csv')